spring:
  profiles: 
  active: dev
---
server:
    profiles: dev 
    application:
       name: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com 
  client:
    # 当前服务是否注册到注册中心
    register-with-eureka: false 
    # true 启动 抛出异常 com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
    # 此客户端是否获取eureka服务器注册表上的注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
    profiles: test 
    application:
       name: microservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com 
  client:
    # 当前服务是否注册到注册中心
    register-with-eureka: false 
    # true 启动 抛出异常 com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
    # 此客户端是否获取eureka服务器注册表上的注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

